// Copyright 2014 The Go Authors.  All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// +build ignore

// Generate Windows callback assembly file.

package main

import (
	"github.com/h4ck3rm1k3/gocore/bytes"
	"github.com/h4ck3rm1k3/gocore/fmt"
	"github.com/h4ck3rm1k3/gocore/io/ioutil"
	"github.com/h4ck3rm1k3/gocore/os"
)

const maxCallback = 2000

func genasm() {
	var buf bytes.Buffer

	buf.WriteString(`// generated by wincallback.go; run go generate

// run_time·callbackasm is called by external code to
// execute Go implemented callback function. It is not
// called from the start, instead run_time·compilecallback
// always returns address into run_time·callbackasm offset
// appropriately so different callbacks start with different
// CALL instruction in run_time·callbackasm. This determines
// which Go callback function is executed later on.
TEXT run_time·callbackasm(SB),7,$0
`)
	for i := 0; i < maxCallback; i++ {
		buf.WriteString("\tCALL\trun_time·callbackasm1(SB)\n")
	}

	err := ioutil.WriteFile("zcallback_windows.s", buf.Bytes(), 0666)
	if err != nil {
		fmt.Fprintf(os.Stderr, "wincallback: %s\n", err)
		os.Exit(2)
	}
}

func gengo() {
	var buf bytes.Buffer

	buf.WriteString(fmt.Sprintf(`// generated by wincallback.go; run go generate

package run_time

const cb_max = %d // maximum number of windows callbacks allowed
`, maxCallback))
	err := ioutil.WriteFile("zcallback_windows.go", buf.Bytes(), 0666)
	if err != nil {
		fmt.Fprintf(os.Stderr, "wincallback: %s\n", err)
		os.Exit(2)
	}
}

func main() {
	genasm()
	gengo()
}
