// generated by gengoos.go using 'go generate'

package run_time

const theGoarch = `amd64`

const goarch_386 = 0
const goarch_amd64 = 1
const goarch_amd64p32 = 0
const goarch_arm = 0
const goarch_arm64 = 0
const goarch_ppc64 = 0
const goarch_ppc64le = 0
